# Generated by Django 5.0.6 on 2024-06-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_coming',
            field=models.BooleanField(default=False),
        ),
    ]
