# Generated by Django 5.0.6 on 2024-06-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_is_coming'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_exclusive',
            field=models.BooleanField(default=False),
        ),
    ]
