# Generated by Django 5.0.6 on 2024-06-13 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_is_exclusive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_exclusive',
            new_name='is_exclusif',
        ),
    ]
